# Generated by Django 3.1.7 on 2021-03-14 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass
import measurement.measures.time
import measurement.measures.volume
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=1024)),
                ('product_price', models.PositiveBigIntegerField()),
                ('product_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), (
                    'THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_rating', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_details', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[
                 ('AREA', 'AREA'), ('MASS', 'MASS'), ('WEIGHT', 'WEIGHT'), ('TIME', 'TIME')], max_length=255, null=True)),
                ('product_volume', django_measurement.models.MeasurementField(
                    blank=True, measurement=measurement.measures.volume.Volume, null=True)),
                ('product_area', django_measurement.models.MeasurementField(
                    blank=True, measurement=measurement.measures.distance.Area, null=True)),
                ('product_mass', django_measurement.models.MeasurementField(
                    blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('product_weight', django_measurement.models.MeasurementField(
                    blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('product_time', django_measurement.models.MeasurementField(
                    blank=True, measurement=measurement.measures.time.Time, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_measurements', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
            options={
                'db_table': 'product_measurements',
            },
        ),
    ]
