# Generated by Django 3.1.7 on 2021-03-15 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0006_auto_20210314_2136"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("user", "product")},
        ),
    ]
