# Generated by Django 3.1.7 on 2021-03-15 11:52
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_auto_20210315_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmeasurements",
            name="product_measurements",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_measurements_id",
                to="cart.product",
            ),
        ),
    ]
