# Generated by Django 3.1.7 on 2021-03-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20210315_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmeasurements',
            name='selection_details',
        ),
    ]
